export const CourseData = [{
    id:1,
    title:'Noorani Qaida Online',
    subTitle: 'Master The Foundation of Quranic Recitation',
    image: '',
    aboutCourse:'In this course, you will learn the essential rules and techniques of Noorani Qaida, a fundamental tool for correct Quranic recitation',
    wPoint1:'Comprehensive Lessons on Quranic Pronunciation',
    wPoint2:'Step-by-Step Guide to Learning Noorani Qaida',
    wPoint3:'Helps with Accurate and Fluent Quranic Recitation',   
    hPoint1:'Learn the essential rules and techniques to read the Quran correctly',
    hPoint2:'Gain an understanding of Tajweed and how to apply it to your recitation',
    hPoint3:'Access content anytime, anywhere, and progress at your own pace',
},{ 
    id:2,
    title:'Learn Quran With Tajweed',
    subTitle: '1',
    image: '1',
    aboutCourse:'',
    wPoint1:'',
    wPoint2:'',
    wPoint3:'',   
    hPoint1:'',
    hPoint2:'',
    hPoint3:'',
}]