export const CourseData = [{
    id:1,
    title:'Noorani Qaida Online',
    subTitle: 'Master The Foundation of Quranic Recitation',
    image: '/images/qot-learn-noorani-qaidah.webp',
    aboutCourse:'In this course, you will learn the essential rules and techniques of Noorani Qaida, a fundamental tool for correct Quranic recitation',
    wPoint1:'Comprehensive Lessons on Quranic Pronunciation',
    wPoint2:'Step-by-Step Guide to Learning Noorani Qaida',
    wPoint3:'Helps with Accurate and Fluent Quranic Recitation',   
    hPoint1:'Learn the essential rules and techniques to read the Quran correctly',
    hPoint2:'Gain an understanding of Tajweed and how to apply it to your recitation',
    hPoint3:'Access content anytime, anywhere, and progress at your own pace',
},{ 
    id:2,
    title:'Learn Quran With Tajweed',
    subTitle: 'Perfect Your Quran Recitation With Tajweed',
    image: '/images/qot-quran-with-tajweed.webp',
    aboutCourse:'Learn to recite the Quran with precision and beauty through our Tajweed-focused Quran reading course. Our qualified instructors will guide you step-by-step in mastering the pronunciation and rules essential for accurate and melodious recitation.',
    wPoint1:'One-on-One Tajweed Sessions',
    wPoint2:'24/7 Access to Practice Resources',
    wPoint3:'Qualified Tajweed Instructors',   
    hPoint1:'',
    hPoint2:'',
    hPoint3:'',
},
{
    id: 3,
    title: 'Quran Memorization',
    subTitle: 'Commit the Holy Quran to Memory',
    image: '/images/qot-quran-memorization.webp',
    aboutCourse: 'This course guides you through the process of memorizing the Quran, offering techniques and support to help you retain and recall the sacred text.',
    wPoint1: 'Structured memorization plans tailored to individual needs',
    wPoint2: 'Regular assessments to monitor progress',
    wPoint3: 'Supportive instructors experienced in Hifz training',
    hPoint1: 'Develop a lifelong connection with the Quran through memorization',
    hPoint2: 'Enhance cognitive abilities and spiritual growth',
    hPoint3: 'Receive Ijazah (certification) upon successful completion',
  },
  {
    id: 4,
    title: 'Tafseer of the Quran',
    subTitle: 'Deepen Your Understanding of the Quranic Verses',
    image: '/images/qot-quran-tafseer.webp',
    aboutCourse: 'Explore the meanings and contexts of Quranic verses, gaining insights into the divine message and its application in daily life.',
    wPoint1: 'Comprehensive analysis of Quranic themes and subjects',
    wPoint2: 'Discussion of historical and cultural contexts',
    wPoint3: 'Interactive sessions encouraging critical thinking',
    hPoint1: 'Gain a profound understanding of the Quran’s message',
    hPoint2: 'Learn to apply Quranic teachings in contemporary situations',
    hPoint3: 'Enhance your spiritual and intellectual connection to Islam',
  },
  {
    id: 5,
    title: 'Learn Arabic Online',
    subTitle: 'Master the Language of the Quran',
    image: '/images/qot-arabic-online-learning.webp',
    aboutCourse: 'This course offers lessons in Arabic language, focusing on reading, writing, and comprehension skills essential for understanding the Quran.',
    wPoint1: 'Step-by-step lessons from basic to advanced levels',
    wPoint2: 'Emphasis on grammar, vocabulary, and pronunciation',
    wPoint3: 'Practical exercises to reinforce learning',
    hPoint1: 'Read and understand Quranic Arabic with confidence',
    hPoint2: 'Enhance your worship through better comprehension of prayers',
    hPoint3: 'Open opportunities for further Islamic studies',
  },
  {
    id: 6,
    title: 'Learn Islamic Studies',
    subTitle: 'Comprehensive Understanding of Islamic Principles',
    image: '/images/qot-islamic-studies-online.webp',
    aboutCourse: 'Delve into various aspects of Islam, including theology, law, and history, to build a solid foundation of Islamic knowledge.',
    wPoint1: 'Detailed study of the Five Pillars of Islam',
    wPoint2: 'Insights into Islamic jurisprudence and ethics',
    wPoint3: 'Exploration of significant events in Islamic history',
    hPoint1: 'Strengthen your faith through informed understanding',
    hPoint2: 'Apply Islamic principles effectively in daily life',
    hPoint3: 'Engage in informed discussions about Islam',
  },
  {
    id: 7,
    title: 'Taleem ul Islam',
    subTitle: 'Essential Islamic Education for Beginners',
    image: '/images/qot-taleem-ul-islam.webp',
    aboutCourse: 'This course introduces the fundamental beliefs and practices of Islam, ideal for new Muslims or those seeking to refresh their knowledge.',
    wPoint1: 'Overview of Islamic creed and theology',
    wPoint2: 'Guidance on performing daily prayers and rituals',
    wPoint3: 'Introduction to Quranic studies and Hadith',
    hPoint1: 'Build a strong foundation in Islamic faith and practice',
    hPoint2: 'Develop confidence in performing religious duties',
    hPoint3: 'Foster a sense of belonging within the Muslim community',
  },
  {
    id: 8,
    title: 'Quran Translation Course',
    subTitle: 'Understand the Quran in Your Language',
    image: '/images/qot-quran-translation.webp',
    aboutCourse: 'Learn to translate Quranic Arabic into your native language, facilitating a deeper connection with the divine text.',
    wPoint1: 'Focus on commonly used Quranic vocabulary',
    wPoint2: 'Techniques for accurate translation and interpretation',
    wPoint3: 'Comparative analysis of different translations',
    hPoint1: 'Access the meanings of the Quran directly',
    hPoint2: 'Enhance personal study and reflection on the Quran',
    hPoint3: 'Contribute to community by sharing translated knowledge',
  },
  {
    id: 9,
    title: 'Online Ijazah Course',
    subTitle: 'Certification in Quranic Recitation and Teaching',
    image: '/images/qot-online-ijazah-course.webp',
    aboutCourse: 'Pursue an Ijazah, authorizing you to teach the Quran, through rigorous training in recitation and memorization.',
    wPoint1: 'Personalized instruction from qualified scholars',
    wPoint2: 'Emphasis on perfecting Tajweed and Qira’at',
    wPoint3: 'Preparation for teaching and transmitting the Quran',
    hPoint1: 'Achieve a recognized certification in Quranic studies',
    hPoint2: 'Preserve the authentic transmission of the Quran',
    hPoint3: 'Empower others by teaching the holy text',
  },
  {
    id: 10,
    title: 'Learn Ten Qirat Online',
    subTitle: 'Master the Ten Recognized Quranic Recitations',
    image: '/images/learn-ten-qirat-online.webp',
    aboutCourse: 'Study the ten Qirat, understanding the variations in recitation and their significance.',
    wPoint1: 'Detailed instruction on each of the ten Qirat',
    wPoint2: 'Historical background and development of Qirat',
    wPoint3: 'Practice sessions to master recitation differences',
    hPoint1: 'Enhance your recitation skills with diverse styles',
    hPoint2: 'Appreciate the richness of Quranic oral traditions',
    hPoint3: 'Qualify to teach multiple recitation methods',
  },
  {
    id: 11,
    title: 'Memorization of Selected Surah',
    subTitle: 'Focus on Memorizing Key Chapters of the Quran',
    image: '/images/qot-quran-memorization.webp',
    aboutCourse: 'Concentrate on memorizing specific Surahs that are frequently recited in prayers and hold significant virtues.',
    wPoint1: 'Guided memorization techniques for selected Surahs',
    wPoint2: 'Understanding the meanings and contexts of the Surahs',
    wPoint3: 'Regular revision to ensure retention',
    hPoint1: 'Enhance your Salah with memorized Surahs',
    hPoint2: 'Gain spiritual benefits associated with specific chapters',
    hPoint3: 'Build confidence in reciting from memory',
  },
  {
    id: 12,
    title: 'Learn Daily Supplication Online',
    subTitle: 'Incorporate Prophetic Duas into Your Routine',
    image: '/images/qot-daily-supplication.webp',
    aboutCourse: 'Learn various daily supplications (duas) taught by the Prophet Muhammad (PBUH) to integrate into your daily life.',
    wPoint1: 'Collection of authentic supplications for different occasions',
    wPoint2: 'Proper pronunciation and memorization of each dua',
    wPoint3: 'Understanding the meanings and contexts of'
}
]